name: CD

on:
  push:
    branches:
      - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'
      - run: git remote set-url --push origin "https://:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: make install
      - run: make docs
